version: '3.5'

services:
    nginx:
        container_name: edm_nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./app:/var/www/web
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    php:
        container_name: edm_php
        build:
            context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/web
        depends_on:
            - mysql

    mysql:
        container_name: edm_mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mysecret
            MYSQL_DATABASE: 'ecole-de-musique'
            MYSQL_USER: edm
            MYSQL_PASSWORD: edm2021!
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql

#    mailcatcher:
#        container_name: edm_mailcatcher
#        image: schickling/mailcatcher:latest
#        ports:
#            - 1588:1080
#            - 1530:1025
#
#    rabbitmq:
#        container_name: edm_rabbitmq
#        image: rabbitmq:3.7.15-management
#        ports:
#            - 60006:15672
#        environment:
#            - RABBITMQ_DEFAULT_USER=admin
#            - RABBITMQ_DEFAULT_PASS=admin
#        volumes:
#            - ./rabbitmq-data:/var/lib/rabbitmq